---
# 1️⃣ Backend Deployment (Flask-ToDo-List)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: traceassist
  labels:
    app: backend
  annotations:
    # track revisions
    deployment.kubernetes.io/revision: "1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
      annotations:
        # enable OTel injection
        instrumentation.opentelemetry.io/inject: "true"
        instrumentation.opentelemetry.io/inject-python: "true"
    spec:
      serviceAccountName: traceassist-sa
      containers:
        - name: backend
          image: taskweb/backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
---
# 2️⃣ Backend Service
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: traceassist
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - port: 5000
      targetPort: 5000
---
# 3️⃣ Frontend Deployment (React)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
spec:
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: frontend
        imagePullPolicy: Never
        ports:
        - containerPort: 3000

---
# 4️⃣ Frontend Service
apiVersion: v1
kind: Service
metadata:
  name: node-app-service
spec:
  type: ClusterIP
  selector:
    app: node-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000